<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Contact Us_1_2</name>
   <tag></tag>
   <elementGuidId>a3f6cf3a-5c66-4731-b5a1-89dfc1ff2839</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='BodyContent_BreadcrumbContent_HyperLink2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BodyContent_BreadcrumbContent_HyperLink2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#BodyContent_BreadcrumbContent_HyperLink2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3c8b06c9-2fb6-4b40-bfb4-b27a48cec214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BodyContent_BreadcrumbContent_HyperLink2</value>
      <webElementGuid>1672ab2f-3808-465d-b4b6-b86ba77ecf22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>linkcolor</value>
      <webElementGuid>0ca1b9e1-89a0-47ad-825e-62728d5ffe15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>contact.aspx</value>
      <webElementGuid>3c0f9d7a-1bee-4a15-be64-20b0f88afb95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Contact Us</value>
      <webElementGuid>3a1f14e3-636f-4f36-8536-a7eb8f7fb9d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BodyContent_BreadcrumbContent_HyperLink2&quot;)</value>
      <webElementGuid>e0056fcb-e034-4dec-827a-3c01e882e3f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='BodyContent_BreadcrumbContent_HyperLink2']</value>
      <webElementGuid>149e2cfb-13c4-4ecc-afc3-4ede5e3cdb76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UpdatePanel1']/div[4]/div/div/ol/li[2]/a</value>
      <webElementGuid>2520bb0b-3777-4f42-8544-9c7767901a0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Contact Us')])[4]</value>
      <webElementGuid>30c8bf00-eda9-42c3-94d3-9b00dd7358b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[1]</value>
      <webElementGuid>daff21a7-eacb-4caa-af4e-da8fb8522a33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exam &amp; Other Enquiry'])[1]/following::a[2]</value>
      <webElementGuid>f0f5e817-80bc-4a1d-a56a-30754073bd1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administration Section'])[1]/preceding::a[1]</value>
      <webElementGuid>49fa0286-63fe-49ea-b29f-fc6be6bf4477</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[5]/preceding::a[1]</value>
      <webElementGuid>200674f0-dc4a-496a-bbd2-098f4e330f36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'contact.aspx')])[5]</value>
      <webElementGuid>7a2ba0fb-82b2-4aad-bfc3-044ab3c7907f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol/li[2]/a</value>
      <webElementGuid>38c7a43c-f7f8-41bf-8256-c0ee007e45bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'BodyContent_BreadcrumbContent_HyperLink2' and @href = 'contact.aspx' and (text() = 'Contact Us' or . = 'Contact Us')]</value>
      <webElementGuid>16199e76-ff5e-47dd-9fcf-2c6d932d126b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
