<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Departments</name>
   <tag></tag>
   <elementGuidId>cbdad409-7a4d-4305-b20c-7df81a795960</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='MenuContent_h1Departments']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#MenuContent_h1Departments</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Departments&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a07b20dc-13a0-48f8-bb7a-9ec5f1bdaad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MenuContent_h1Departments</value>
      <webElementGuid>0604834b-7c37-43bf-b0ce-79addade5380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>b1675a13-7b74-46c8-89da-c1b66e24abaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Departments</value>
      <webElementGuid>8088a843-70d5-4b7b-bb4c-a88e5b621abe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MenuContent_h1Departments&quot;)</value>
      <webElementGuid>5c15c339-d5bd-48c1-bd7a-872b14187856</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='MenuContent_h1Departments']</value>
      <webElementGuid>6f6e1e19-fef2-4f8c-ae69-d11c30d8af2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cssmenu']/ul/li[2]/a</value>
      <webElementGuid>219811e9-c26c-4feb-a656-4796a7bb29dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Departments')]</value>
      <webElementGuid>65ca3ed6-b5ac-4b8a-95a1-fe82d0092404</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About University'])[1]/following::a[1]</value>
      <webElementGuid>5a37cac6-4189-4bd1-80a2-5c7bfa10ebb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aims &amp; Objectives'])[1]/following::a[2]</value>
      <webElementGuid>6d75f3a9-f111-42a9-a9d3-4fb374076944</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Applied Electronics'])[1]/preceding::a[1]</value>
      <webElementGuid>233619a0-76d5-49d4-afb0-f78a535e860d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Biotechnology'])[1]/preceding::a[2]</value>
      <webElementGuid>2bc8fe15-312b-4b7d-9bb8-4767cdbbebde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Departments']/parent::*</value>
      <webElementGuid>6d44c283-c707-40b7-bdbc-e4b2f60213a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[8]</value>
      <webElementGuid>2e3cc834-37da-4101-b107-bcaf5e0d88e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>a838019b-695d-4ae2-a1ca-1eb4faff57ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'MenuContent_h1Departments' and @href = '#' and (text() = 'Departments' or . = 'Departments')]</value>
      <webElementGuid>1a4bb9fa-19f1-47ba-a4fb-6af8baeaa3e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
