<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Exam Results</name>
   <tag></tag>
   <elementGuidId>3fca65ea-b701-4ac7-8e71-ca90bc332959</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='MenuContent_h1examresult']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#MenuContent_h1examresult</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#MenuContent_h1examresult</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>76cc70c2-24ee-41fd-ad1c-3555a50a4702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MenuContent_h1examresult</value>
      <webElementGuid>2474f00e-306c-419b-a2de-cc41952a2a70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Examination/ExamResult.aspx</value>
      <webElementGuid>a62b5e3c-babc-4930-b5b3-afb7adfc5993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Exam Results</value>
      <webElementGuid>9ec28898-1f5b-4ef9-9788-2222e53bf4ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MenuContent_h1examresult&quot;)</value>
      <webElementGuid>ea72006e-bb17-4dfa-af7d-93ed8df378fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='MenuContent_h1examresult']</value>
      <webElementGuid>27d942f2-f000-4c1f-b504-7607d398bc43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cssmenu']/ul/li[5]/ul/li[5]/a</value>
      <webElementGuid>9ef472f4-e1b3-457f-a7e6-37fe347c58d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Exam Results')]</value>
      <webElementGuid>6b72a353-096c-4b31-94e1-f55cad8b0c49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='News &amp; Announcements'])[1]/following::a[1]</value>
      <webElementGuid>18e728db-3888-449b-aa68-b22c57221ebf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Press Note'])[1]/following::a[2]</value>
      <webElementGuid>f9d220c3-1da5-4539-b4ba-c0f7f9fcf4fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subject Abbreviations'])[1]/preceding::a[1]</value>
      <webElementGuid>4cce8513-b70e-4488-9897-0549a2eeed9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admission Card'])[1]/preceding::a[2]</value>
      <webElementGuid>fad093d1-f5dd-4110-b4b8-ec4c98b31350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Exam Results']/parent::*</value>
      <webElementGuid>5c9c81a1-17e4-4c9d-9d03-aaa64689752b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'Examination/ExamResult.aspx')]</value>
      <webElementGuid>7c8903a4-af2d-4d20-a94d-b607878026ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/ul/li[5]/a</value>
      <webElementGuid>debdaa69-07a6-42cb-86f6-f530117986aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'MenuContent_h1examresult' and @href = 'Examination/ExamResult.aspx' and (text() = 'Exam Results' or . = 'Exam Results')]</value>
      <webElementGuid>52c79734-e311-43ee-bec6-91fcbfd3c6c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
