<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Examination_1</name>
   <tag></tag>
   <elementGuidId>6ec166a0-b649-4bbc-b410-12b31a5fbdcf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='BodyContent_BreadcrumbContent_HyperLink2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BodyContent_BreadcrumbContent_HyperLink2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#BodyContent_BreadcrumbContent_HyperLink2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1a10c183-29f5-4f4e-8622-c6cf0b85185c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BodyContent_BreadcrumbContent_HyperLink2</value>
      <webElementGuid>26390077-b812-4c2b-8c88-c01873b2a880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>linkcolor</value>
      <webElementGuid>dcb52d8a-f3be-4774-b26d-b09126e0a0f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>contact.aspx</value>
      <webElementGuid>6ec79af9-be0a-4fd9-8ec2-f4e7898752aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Examination</value>
      <webElementGuid>df39d860-af42-41b5-84a7-871527b34b1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BodyContent_BreadcrumbContent_HyperLink2&quot;)</value>
      <webElementGuid>c53c766f-70d9-46c4-a864-6099ae92e424</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='BodyContent_BreadcrumbContent_HyperLink2']</value>
      <webElementGuid>d0f9cf48-c8fe-445d-90f0-60d4bf051904</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UpdatePanel1']/div[4]/div/div/ol/li[2]/a</value>
      <webElementGuid>3786b785-d6c6-480f-b6e8-a834641dc986</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Examination')])[4]</value>
      <webElementGuid>77e0f9fe-bbb4-44ea-8085-4c947936f042</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[1]</value>
      <webElementGuid>5ee7db9b-cf60-4b8b-bc84-202bef52fdb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exam &amp; Other Enquiry'])[1]/following::a[2]</value>
      <webElementGuid>889e82a8-e62a-4285-8825-fd9c1d891e9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About Examination Section'])[1]/preceding::a[1]</value>
      <webElementGuid>a21decf7-a7d6-4c99-b0ff-59c6dbe9a75a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Board of Examinations and Evaluation'])[1]/preceding::a[1]</value>
      <webElementGuid>715675bb-35a7-4663-bcbc-b776fe128f30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'contact.aspx')])[5]</value>
      <webElementGuid>d20bb2d3-9d9f-423c-8715-51ef483a0ede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol/li[2]/a</value>
      <webElementGuid>6e2a8128-b5c3-4292-8ff6-b4eeac3f19bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'BodyContent_BreadcrumbContent_HyperLink2' and @href = 'contact.aspx' and (text() = 'Examination' or . = 'Examination')]</value>
      <webElementGuid>93cd1cb3-719e-4c06-841e-d33f15a49481</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
