<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Google Map</name>
   <tag></tag>
   <elementGuidId>d213b086-0c4e-467d-ac29-3c0d0b0826c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='FooterContent_h1googlemap']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FooterContent_h1googlemap</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Google Map&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>019ef951-b543-4091-8c66-acf3f7c98d66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FooterContent_h1googlemap</value>
      <webElementGuid>8f34cb97-3893-458e-92c9-ecaf57f548ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Google Map</value>
      <webElementGuid>99998bca-893a-4ae6-bcb1-36cae242be17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FooterContent_h1googlemap&quot;)</value>
      <webElementGuid>aede6742-32b0-48e7-8a1b-af14c131099b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='FooterContent_h1googlemap']</value>
      <webElementGuid>0a252014-8c6d-4a6b-a22a-33b7bf2d97b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UpdatePanel1']/div[4]/div/div/div/div[4]/h4/a</value>
      <webElementGuid>64c97546-97a1-47fe-b756-fd58afd76324</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Google Map')]</value>
      <webElementGuid>b7bcf293-0b1d-4b3d-9063-6618d74e82bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hit Counter'])[1]/following::a[1]</value>
      <webElementGuid>d1dbe430-44d3-464e-8176-1c8749c32231</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check Mail'])[1]/following::a[2]</value>
      <webElementGuid>5ce6dc3e-0a43-4c59-966e-fd0b1f46c7ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Develope By'])[1]/preceding::a[2]</value>
      <webElementGuid>969b16b5-a7b0-4bd8-be8c-c3ff546481af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Google Map']/parent::*</value>
      <webElementGuid>bf7fcc5e-523b-47a5-b8ec-627cf1ac8a05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/h4/a</value>
      <webElementGuid>d7c75285-333c-4463-bba9-6bace84d53fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'FooterContent_h1googlemap' and (text() = 'Google Map' or . = 'Google Map')]</value>
      <webElementGuid>966884a7-3099-4441-beeb-0d916e94deda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
