<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_List of All Examinations Subject Abbrevia_5f6450</name>
   <tag></tag>
   <elementGuidId>43a1d41d-0d2b-42ff-8422-dd9f57e4ef8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='BodyContent_SubBodyContent_HyperLink3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BodyContent_SubBodyContent_HyperLink3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;List of All Examinations Subject Abbreviations/Code&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3e4e67b8-6d19-4b61-9f9c-4cb00eca1550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BodyContent_SubBodyContent_HyperLink3</value>
      <webElementGuid>499ece42-9c68-4b0e-b6c7-8418e2491f3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>pdf/ICR_SUB-CODE-WINTER-2019.pdf</value>
      <webElementGuid>9a17cfec-20f2-4016-af89-9cf0cf63a4c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>a8719b2e-39d9-44e0-a67b-bcccfd06efc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>List of All Examinations Subject Abbreviations/Code  </value>
      <webElementGuid>a052fe32-5a27-43c7-aeeb-802ac71f6270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BodyContent_SubBodyContent_HyperLink3&quot;)</value>
      <webElementGuid>95067839-07ac-4e7d-b1b0-69e3afd17536</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='BodyContent_SubBodyContent_HyperLink3']</value>
      <webElementGuid>c1bf92e9-fffe-4f39-a1ff-c165c0d5f6c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/ul/li/a</value>
      <webElementGuid>505482d5-1bcf-4382-920c-d3115e186529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'List of All Examinations Subject Abbreviations/Code')]</value>
      <webElementGuid>a8b8ecbb-b8f7-4116-9188-15d5eef6a7f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List of Subject Abbreviations'])[1]/following::a[1]</value>
      <webElementGuid>ec3d5ec7-0442-4c41-9e51-a8b2b806e649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subject Abbrivations'])[1]/following::a[1]</value>
      <webElementGuid>981049d5-990b-4895-999d-96cd07d6b80e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Examination Office'])[2]/preceding::a[1]</value>
      <webElementGuid>5c80210b-e6ec-4611-95b6-c804e714a08a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time Table'])[2]/preceding::a[2]</value>
      <webElementGuid>64877027-7898-4796-bc78-4c5586428bc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='List of All Examinations Subject Abbreviations/Code']/parent::*</value>
      <webElementGuid>9505d197-5fb8-4c55-8e9f-ee48cece658d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'pdf/ICR_SUB-CODE-WINTER-2019.pdf')]</value>
      <webElementGuid>7e42662e-6aca-468b-b602-ed15a155c31e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li/a</value>
      <webElementGuid>38145ea5-884a-407b-8467-b9c565c8e71f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'BodyContent_SubBodyContent_HyperLink3' and @href = 'pdf/ICR_SUB-CODE-WINTER-2019.pdf' and (text() = 'List of All Examinations Subject Abbreviations/Code  ' or . = 'List of All Examinations Subject Abbreviations/Code  ')]</value>
      <webElementGuid>e656c77a-324b-43c8-b9fb-7d4f31df1a04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
