<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_RIGHT TO PUBLIC SERVICES ACT - YOUR SERVI_e857d1</name>
   <tag></tag>
   <elementGuidId>a7845e9e-f875-4fd6-90cc-92824ebc4070</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='FooterContent_h1mahaonlineNew']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FooterContent_h1mahaonlineNew</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;RIGHT TO PUBLIC SERVICES ACT - YOUR SERVICE IS OUR DUTY&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f1e62df7-4851-4d7a-9185-7a8ec043bdb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FooterContent_h1mahaonlineNew</value>
      <webElementGuid>68aa57be-53e9-4e73-a071-6ecef1cec9ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://aaplesarkar.mahaonline.gov.in</value>
      <webElementGuid>597d1e6a-11b7-4043-9112-2599f441ee60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>dfbcc380-c362-4b35-bf01-ebd7f9083d18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RIGHT TO PUBLIC SERVICES ACT - YOUR SERVICE IS OUR DUTY</value>
      <webElementGuid>054c1ab4-496d-4d83-a4e1-d0b1f527d4fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FooterContent_h1mahaonlineNew&quot;)</value>
      <webElementGuid>be742624-dac0-495e-a7fd-603fe7c004d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='FooterContent_h1mahaonlineNew']</value>
      <webElementGuid>97ac982b-327c-4635-8a94-d7e2f35e07a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UpdatePanel1']/div[4]/div/div/div/div/ul/li[7]/a</value>
      <webElementGuid>ccd4834f-70f0-4e1d-8df8-352061518aee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'RIGHT TO PUBLIC SERVICES ACT - YOUR SERVICE IS OUR DUTY')]</value>
      <webElementGuid>5b11f575-f6eb-47e9-86aa-5fb2bf0974e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mahaonline'])[1]/following::a[1]</value>
      <webElementGuid>c83b41a5-cfec-4aca-af9d-054233aba80e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consortium for Educational Communi'])[1]/following::a[2]</value>
      <webElementGuid>b35125b2-0873-4ad4-aecc-526215555801</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Student Corner'])[1]/preceding::a[1]</value>
      <webElementGuid>83682c0f-8bf4-476b-87b2-ac048d74bac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sakshat'])[1]/preceding::a[2]</value>
      <webElementGuid>8eb8a0cf-d2bc-4e07-b6b2-8e5833878657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='RIGHT TO PUBLIC SERVICES ACT - YOUR SERVICE IS OUR DUTY']/parent::*</value>
      <webElementGuid>ec19e45e-855d-43f6-9ff4-4506dbbcd6fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://aaplesarkar.mahaonline.gov.in')]</value>
      <webElementGuid>0764626e-7bcc-4ea7-9d62-f9b9ce07bea5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/ul/li[7]/a</value>
      <webElementGuid>cb956d9b-6666-4f16-af01-6cf781a2fc7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'FooterContent_h1mahaonlineNew' and @href = 'https://aaplesarkar.mahaonline.gov.in' and (text() = 'RIGHT TO PUBLIC SERVICES ACT - YOUR SERVICE IS OUR DUTY' or . = 'RIGHT TO PUBLIC SERVICES ACT - YOUR SERVICE IS OUR DUTY')]</value>
      <webElementGuid>d792be2b-6afc-4e39-9d52-9cd48e405d91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
