<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SSR</name>
   <tag></tag>
   <elementGuidId>253788ea-8ae1-4b87-8c98-fbe50ab6e621</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='MenuContent_HplnkNAAC1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#MenuContent_HplnkNAAC1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;SSR&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2745e355-1f63-482c-b66e-bdf680cf29fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MenuContent_HplnkNAAC1</value>
      <webElementGuid>fccfd5be-5a6b-4d5e-92b1-1d05c0c13390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>IQAC/pdf/SSR%20-%20SGBAU%20-%204th%20Cycle.pdf</value>
      <webElementGuid>b50d83d4-3241-4ccd-aaef-86a8488de612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SSR</value>
      <webElementGuid>632e52a0-212b-4e8a-a0bf-bcb68b2a7545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MenuContent_HplnkNAAC1&quot;)</value>
      <webElementGuid>37449d05-6d74-466f-ba6c-2e4c326a1331</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='MenuContent_HplnkNAAC1']</value>
      <webElementGuid>7131b348-5f71-401f-b908-45b2ff6af151</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cssmenu']/ul/li[6]/ul/li/a</value>
      <webElementGuid>852aaec9-6ac4-4453-a319-6bb159be8b50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'SSR')]</value>
      <webElementGuid>115d7972-b85b-4ff9-ac49-d1e957b44b01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[1]/following::a[2]</value>
      <webElementGuid>7ff9107a-2511-40a0-97ad-d6f31ca1b4b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GIC Timetable'])[1]/following::a[3]</value>
      <webElementGuid>6f6e9117-1a5d-4782-b62e-913666d6f5f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DATA TEMPLATES'])[1]/preceding::a[1]</value>
      <webElementGuid>ed218dea-8ca8-46fb-a5d4-b2b264bfcac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AQAR 2015-2016'])[1]/preceding::a[3]</value>
      <webElementGuid>7c7f42c9-bf37-48ea-8b7f-0869e5a95987</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SSR']/parent::*</value>
      <webElementGuid>be395126-5888-4f2d-99b7-ef92df2dc69f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'IQAC/pdf/SSR%20-%20SGBAU%20-%204th%20Cycle.pdf')]</value>
      <webElementGuid>93c5a654-5472-47ea-b4de-dc3466ba3068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/ul/li/a</value>
      <webElementGuid>2f557612-cb85-4e58-b701-9099cfabe0f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'MenuContent_HplnkNAAC1' and @href = 'IQAC/pdf/SSR%20-%20SGBAU%20-%204th%20Cycle.pdf' and (text() = 'SSR' or . = 'SSR')]</value>
      <webElementGuid>7f81efe9-688f-4c9d-96ad-6fecdce9ea57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
