<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Google Map_FooterContent_googlemapimg</name>
   <tag></tag>
   <elementGuidId>f5aecc38-9807-464f-aa95-ba83bb5860b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='FooterContent_googlemapimg']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FooterContent_googlemapimg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(4) > a >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8fe3f0ab-9d9c-41dc-905d-3e3e992adfd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FooterContent_googlemapimg</value>
      <webElementGuid>4e9526ff-8ce2-480b-9607-12834822acab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../images/googleimage.jpg</value>
      <webElementGuid>fbb4b97a-3908-4847-b336-d6cd73287626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FooterContent_googlemapimg&quot;)</value>
      <webElementGuid>154b7954-2c16-49d5-a483-2044df83953f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='FooterContent_googlemapimg']</value>
      <webElementGuid>2b5ff28c-7294-4f84-bb21-48239626a571</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UpdatePanel1']/div[4]/div/div/div/div[4]/a/img</value>
      <webElementGuid>277bdef0-6140-4dff-aca0-8df7f5546f72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a/img</value>
      <webElementGuid>83ff9695-ab07-4e35-aebc-8f3be6b3a28c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'FooterContent_googlemapimg' and @src = '../../images/googleimage.jpg']</value>
      <webElementGuid>02158b1f-bdd6-4aa4-9138-95090aefc06f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
