<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Research</name>
   <tag></tag>
   <elementGuidId>d322340d-62b6-446d-b456-26cd1f2c48d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='about']/div/div/div/ol/li[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ol.breadcrumb > li:nth-of-type(4)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Research&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>d9cfb91a-95ba-422a-8e31-357243252847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Research</value>
      <webElementGuid>8970a9cc-d404-4db7-8fd3-5c750529aa33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;about&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;col-md-12&quot;]/ol[@class=&quot;breadcrumb&quot;]/li[4]</value>
      <webElementGuid>9cde58ba-e38e-406c-a859-afac8a8185de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='about']/div/div/div/ol/li[4]</value>
      <webElementGuid>306e5583-652f-448b-b4df-8fd2aa5500c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Applied Electronics'])[2]/following::li[1]</value>
      <webElementGuid>76bf0be6-d4e1-4a93-a656-ccc35845de33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Departments'])[2]/following::li[2]</value>
      <webElementGuid>fccec0ee-968c-481f-b498-22b1a124d3f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ongoing Research Projects'])[1]/preceding::li[1]</value>
      <webElementGuid>b8d0f961-105e-4a6d-b024-380a3ac92beb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sr. No'])[1]/preceding::li[1]</value>
      <webElementGuid>bf680b0e-f48a-42d0-9a3b-4ef7f8cb560d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Research']/parent::*</value>
      <webElementGuid>5dc15e22-d5bc-46e8-b0d3-6f33ef6d7f05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol/li[4]</value>
      <webElementGuid>d456e62f-c414-4ed8-97a9-c5bdee46d8aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Research' or . = 'Research')]</value>
      <webElementGuid>ff913116-807f-491f-a585-b7545f0dbffa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
