<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Office Phone  0721-2668273 Ext.No. 203</name>
   <tag></tag>
   <elementGuidId>84e1578f-84e9-4311-8719-534134b72569</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#content > p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Office Phone : 0721-2668273 Ext.No. 203&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>5f9d9f68-c866-4e60-878d-187f90f78729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>aae690e5-217f-49b5-b53e-09df38ef4d12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Office Phone : 0721-2668273 Ext.No. 203</value>
      <webElementGuid>c7f099da-934c-431c-8fda-5b9c945fab92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/p[1]</value>
      <webElementGuid>dbbb6e0f-e6d7-436b-b9a8-b1348414f1b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/p</value>
      <webElementGuid>eb13dbaf-865e-4338-a825-7b307a52cfba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email : vc@sgbau.ac.in'])[1]/following::p[1]</value>
      <webElementGuid>b61a14dd-5c47-4d08-bef6-8039dd3cb02d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dr.  Milind A. Barhate'])[1]/following::p[1]</value>
      <webElementGuid>c3f12b8c-d6b7-46e5-b4cc-8d6e37247793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pro Vice-Chancellor'])[1]/preceding::p[1]</value>
      <webElementGuid>ceca9c9a-9966-4070-b47d-767cd37a44ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email : provc@sgbau.ac.in'])[1]/preceding::p[1]</value>
      <webElementGuid>766a647f-1d32-459b-9c3a-f879d933293f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Office Phone : 0721-2668273 Ext.No. 203']/parent::*</value>
      <webElementGuid>54abd857-e7e3-4534-a915-5e42f46b71ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/p</value>
      <webElementGuid>ed5d9ebf-1454-4a28-8e9c-87282d727b41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Office Phone : 0721-2668273 Ext.No. 203' or . = 'Office Phone : 0721-2668273 Ext.No. 203')]</value>
      <webElementGuid>d46501c3-c166-46e9-b319-b4a6ac43c3de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
