<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Name of funding agency</name>
   <tag></tag>
   <elementGuidId>01582baa-9777-48a2-b976-8b331297984a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/table/thead/tr/th[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>th:nth-of-type(4)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Name of funding agency&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>7957b4d2-86d8-47ef-b2d1-3b5a28fbd60f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>14%</value>
      <webElementGuid>18fdc939-6ca3-4af3-ae5e-528518ad39fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Name of funding agency </value>
      <webElementGuid>abe78e88-0734-442a-a52a-3307c39d3e2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/table[@class=&quot;table table-bordered&quot;]/thead[1]/tr[1]/th[4]</value>
      <webElementGuid>64eeaf5c-de66-4d91-ac23-c36d90ef1710</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/table/thead/tr/th[4]</value>
      <webElementGuid>ea0e94ef-90f7-447a-937d-a0a9ec0ba052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Program/ Project title'])[1]/following::th[1]</value>
      <webElementGuid>d44c1605-cc07-4e52-83fd-ccf2b6149b35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name of the teacher'])[1]/following::th[2]</value>
      <webElementGuid>814a6218-04fb-4606-a103-032f4d4123ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Duration of the project'])[1]/preceding::th[1]</value>
      <webElementGuid>b8b40c85-aa77-4d39-85ca-08e623fd8383</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amount'])[1]/preceding::th[2]</value>
      <webElementGuid>dc5c2ded-a007-40cf-94fd-00abef4594e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Name of funding agency']/parent::*</value>
      <webElementGuid>75a9ebcf-82ec-45ef-bf00-232c888f7aa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[4]</value>
      <webElementGuid>773259ef-3a51-4804-b8ef-58fb1634003d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = ' Name of funding agency ' or . = ' Name of funding agency ')]</value>
      <webElementGuid>4f4d9830-7228-4e43-909f-1838e6e1b713</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
